#!/bin/bash
#PBS -S /bin/bash
#PBS -l nodes=1:ppn=1 -q cerbero
#PBS -N HydraGNN
#PBS -o out-hostname-XyZ-N1x1-qsub.txt
#PBS -j oe
#PBS -e out-hostname-XyZ-N1x1.txt
cd ${PBS_O_WORKDIR}
OUT_DIR=/u/archive/laureandi/nebolosi/HydraGNN/hydragnn/FreeFEM/output
export mkPrefix=/u/sw
source ${mkPrefix}/etc/profile
module load gcc-glibc/11.2.0
cd /u/archive/laureandi/nebolosi/HydraGNN/hydragnn/FreeFEM/
python3.9 test.py &>${OUT_DIR}/stdout_split.txt