#!/bin/bash
#PBS -S /bin/bash
#PBS -l nodes=1:ppn=1,walltime=200:00:00 -q cerbero
#PBS -N Training-complex
#PBS -j oe
#PBS -o /u/nebolosi/stdout.txt
#PBS -e /u/nebolosi/stderr.txt
cd ${PBS_O_WORKDIR}
OUT_DIR=/u/archive/laureandi/nebolosi/HydraGNN/hydragnn/FreeFEM/output
export mkPrefix=/u/sw
source ${mkPrefix}/etc/profile
module load gcc-glibc/11.2.0
cd /u/archive/laureandi/nebolosi/HydraGNN/hydragnn/FreeFEM/
python3.9 training.py --inputfile custom-complex.json &>${OUT_DIR}/stdout_complex.txt